# Generated by Django 5.1.1 on 2024-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='complain_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='admission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='transfer',
            field=models.IntegerField(default=0),
        ),
        
    ]
