# Generated by Django 5.1.1 on 2024-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_admission_transfer_patient_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admission_transfer',
        ),
        migrations.AddField(
            model_name='patient',
            name='admission',
            field=models.CharField(choices=[('Select', 'Select'), ('Nil', 'Nil'), ('Chris Hani Baragwanath Hospital (Johannesburg)', 'Chris Hani Baragwanath Hospital (Johannesburg)'), ('Charlotte Maxeke Johannesburg Academic Hospital (Johannesburg)', 'Charlotte Maxeke Johannesburg Academic Hospital (Johannesburg)'), ('Tygerberg Hospital (Cape Town)', 'Tygerberg Hospital (Cape Town)'), ('Steve Biko Academic Hospital (Pretoria)', 'Steve Biko Academic Hospital (Pretoria)'), ('Groote Schuur Hospital (Cape Town)', 'Groote Schuur Hospital (Cape Town)'), ('Nelson Mandela Academic Hospital (Eastern Cape)', 'Nelson Mandela Academic Hospital (Eastern Cape)'), ('Mamelodi Hospital (Gauteng)', 'Mamelodi Hospital (Gauteng)')], default='Select', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='transfer',
            field=models.CharField(choices=[('Select', 'Select'), ('Nil', 'Nil'), ('Chris Hani Baragwanath Hospital (Johannesburg)', 'Chris Hani Baragwanath Hospital (Johannesburg)'), ('Charlotte Maxeke Johannesburg Academic Hospital (Johannesburg)', 'Charlotte Maxeke Johannesburg Academic Hospital (Johannesburg)'), ('Tygerberg Hospital (Cape Town)', 'Tygerberg Hospital (Cape Town)'), ('Steve Biko Academic Hospital (Pretoria)', 'Steve Biko Academic Hospital (Pretoria)'), ('Groote Schuur Hospital (Cape Town)', 'Groote Schuur Hospital (Cape Town)'), ('Nelson Mandela Academic Hospital (Eastern Cape)', 'Nelson Mandela Academic Hospital (Eastern Cape)'), ('Mamelodi Hospital (Gauteng)', 'Mamelodi Hospital (Gauteng)')], default='Select', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='complain_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Select', max_length=10),
        ),
    ]
